apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-datasource
  labels:
     grafana_datasource: "1"
data:
  tempo-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        uid: tempo
        url: http://my-tempo-query-frontend.tempo.svc:3100
        access: proxy
        jsonData:
          tracesToLogsV2:
            customQuery: false
            datasourceUid: loki
            filterBySpanID: true
            filterByTraceID: true
            tags:
              - key: service.name
                value: job
          tracesToMetrics:
            datasourceUid: mimir
            tags:
              - key: service.name
                value: job
          serviceMap:
            datasourceUid: mimir
          lokiSearch:
            datasourceUid: loki
          search:
            hide: false
          nodeGraph:
            enabled: true