apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  annotations:
    {{- include "collector.annotations" . | nindent 4 }}
  labels:
    {{- include "collector.labels" . | nindent 4 }}
data:
  otel-collector-config: |
    extensions:
      zpages:
        endpoint: 0.0.0.0:55679
      health_check:
      memory_ballast:
        size_in_percentage: 40

    receivers:
      fluentforward:
        endpoint: 0.0.0.0:24224
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25

      attributes:
        actions:
          - action: insert
            key: loki.format
            value: json

    exporters:
      otlp/tempo:
        endpoint: "http://my-tempo-distributor.tempo.svc:4317"
        tls:
          insecure: true

      prometheusremotewrite/mimir:
        endpoint: "http://my-mimir-distributor.mimir.svc:8080/api/v1/push"
        headers:
          X-Scope-OrgID: "anonymous"

      loki:
        endpoint: "http://my-loki-loki-distributed-distributor.loki.svc:3100/loki/api/v1/push"

      # Optional exporters



    service:
      telemetry:
        metrics:
          address: ":8888"
        logs:
          level: {{ .Values.config.logLevel }}

      extensions: 
      - zpages
      - memory_ballast
      - health_check
     
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp/tempo]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters:
          - prometheusremotewrite/mimir
        
       
        logs:
          receivers: [otlp, fluentforward]
          processors: [memory_limiter, batch]
          exporters: [loki]