apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-datasource
  labels:
     grafana_datasource: "1"
data:
  mimir-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Mimir
        type: prometheus
        uid: mimir
        url: http://my-mimir-query-frontend.mimir.svc:8080/prometheus
        isDefault: true
        jsonData:
          # This is required due to multi-tenant support and the fact that we are not
          # currently running an nginx frontend, which would add this header
          httpHeaderName1: "X-Scope-OrgID"
          prometheusType: "Mimir"
          prometheusVersion: "2.6.0"
        secureJsonData:
          httpHeaderValue1: "anonymous"