# https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/values.yaml
# CHANGELOG for Mimir releases: https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/CHANGELOG.md

# Global vars for all environments

commonAnnotations: &commonAnnotations
  owner: aravind
  product: aravind


mimir-distributed:
  global:
    # Ensure we have our required annotations
    podAnnotations: *commonAnnotations

  metaMonitoring:
    dashboards:
      enabled: true
      annotations:
        grafana_folder: "APM Tools"

    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
      mimirAlerts: true

  # We are using S3
  minio:
    enabled: false


  # Allows overriding Mimir configuration values
  structuredConfig:
    limits:
      # Want to enable exemplars
      max_global_exemplars_per_user: 100000


  # Below are settings for the various services

  alertmanager:
    persistentVolume:
      enabled: false
    service:
      annotations: *commonAnnotations


  compactor:
    persistentVolume:
      enabled: false
    service:
      annotations: *commonAnnotations

  

  distributor:
    service:
      annotations: *commonAnnotations




  ingester:
    service:
      annotations: *commonAnnotations

    replicas: 3   # Request at least 1 per AZ
    persistentVolume:
      enabled: false


  # TODO: Should be using a gateway section anyway.  Revisit
  nginx:
    enabled: false
    service:
      annotations: *commonAnnotations

  overrides_exporter:
    enabled: false
    service:
      annotations: *commonAnnotations

  querier:
    replicas: 1
    service:
      annotations: *commonAnnotations


  query_frontend:
    service:
      annotations: *commonAnnotations

  query_scheduler:
    replicas: 1
    service:
      annotations: *commonAnnotations


  # This is not deploying correct - if we want to use it, will
  # have to make further updates
  rollout_operator:
    enabled: false

  ruler:
    service:
      annotations: *commonAnnotations


  store_gateway:
    service:
      annotations: *commonAnnotations
    replicas: 1
    persistentVolume:
      enabled: false
      size: 2Gi
