apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-datasource
  labels:
     grafana_datasource: "1"
data:
  prometheus-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://prometheus-operated.prometheus.svc:9090