{{- with .Values.monitoring.dashboards }}
{{- if .enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki.dashboardsName" $ }}-4
  namespace: {{ .namespace | default $.Release.Namespace }}
  labels:
    {{- include "loki.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    grafana_folder: "APM Tools Compiled"
data:
  "loki-chunks.json": |
    {{ $.Files.Get "src/dashboards-compiled/loki-chunks.json" | fromJson | toJson }}
  "loki-deletion.json": |
    {{ $.Files.Get "src/dashboards-compiled/loki-deletion.json" | fromJson | toJson }}
  "loki-logs.json": |
    {{ $.Files.Get "src/dashboards-compiled/loki-logs.json" | fromJson | toJson }}
  "loki-mixin-recording-rules.json": |
    {{ $.Files.Get "src/dashboards-compiled/loki-mixin-recording-rules.json" | fromJson | toJson }}
  "loki-operational.json": |
    {{ $.Files.Get "src/dashboards-compiled/loki-operational.json" | fromJson | toJson }}
{{- end -}}
{{- end -}}