apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-datasource
  labels:
     grafana_datasource: "1"
data:
  loki-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki
        url: http://my-loki-loki-distributed-query-frontend.loki:3100
        access: proxy
        jsonData:
          derivedFields:
            - datasourceUid: tempo
              #matcherRegex: '\"(?:traceid|trace_id)\":\"(\w+)\"'
              matcherRegex: '[\"| ](?:traceid|trace_id|traceID)(?:\":\"|=)(\w+)[\"| ]'
              name: TraceID
              url: '$${__value.raw}'