# Reference: https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/values.yaml
# To debug changes: helm template . --debug




commonannotations: &commonAnnotations
  owner: aravind
  product: aravind


config:
  logLevel: info



annotations: *commonAnnotations

### Values for the OTEL chart
opentelemetry-collector:
  annotations: *commonAnnotations

  service:
    annotations:
      <<: *commonAnnotations

  podAnnotations: *commonAnnotations

  mode: deployment


  resources:
    limits:
      cpu: 50m
      memory: 100Mi
    requests:
      cpu: 50m
      memory: 100Mi





  ports:
    otlp:
      enabled: true
    otlp-http:
      enabled: true
    jaeger-compact:
      enabled: false
    jaeger-thrift:
      enabled: false
    zipkin:
      enabled: false
    metrics:
      enabled: true
    zpages:
      enabled: true
      containerPort: 55679
      servicePort: 55679
      hostPort: 55679
      protocol: TCP
    health:
      enabled: true
      containerPort: 13133
      servicePort: 13133
      hostPort: 13133
      protocol: TCP
    loki:
      enabled: true
      containerPort: 3500
      servicePort: 3500
      hostPort: 3500
      protocol: TCP

  autoscaling:
    enabled: false

  # replicaCount: 3

  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1

  serviceMonitor:
    enabled: true

  config:
    exporters:
      otlp/tempo:
        endpoint: "http://my-tempo-distributor.tempo.svc:4317"
        tls:
          insecure: true

      prometheusremotewrite/mimir:
        endpoint: "http://my-mimir-distributor.mimir.svc:8080/api/v1/push"
        headers:
          X-Scope-OrgID: "anonymous"

      loki:
        endpoint: "http://my-loki-loki-distributed-distributor.loki.svc:3100/loki/api/v1/push"

    extensions:
      zpages:
        endpoint: ${env:MY_POD_IP}:55679

    processors:
      # Nothing to add here right now

    receivers:
      # Disable already defined receivers that we don't want
      jaeger: null
      prometheus: null
      zipkin: null

      # Enable any additional receivers we want

      loki:
        protocols:
          http:
            endpoint: ${env:MY_POD_IP}:3500
            
          grpc:
            endpoint: ${env:MY_POD_IP}:3600            
        

    service:
      # Add ability to change logging level
#      telemetry:
#        logs:
#          level: {{ tpl .Values.config.logLevel . }}

      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp/tempo]
        metrics:
          receivers: [otlp]
          exporters: [prometheusremotewrite/mimir]
        logs:
          receivers: [otlp, loki]
          exporters: [loki]